services:
  postgres:
    image: postgres:16
    container_name: retail_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retail_pass
      POSTGRES_DB: retail_sales
    ports:
      - "5433:5432"
    volumes:
      - retail_pg_data:/var/lib/postgresql/data

volumes:
  retail_pg_data: